name: Test Output

on:
  push:
    branches: 
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main workflow"
      
  workspace:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir newdir && touch newdir/newfile
      - run: |
          echo "NEW_DIR is $NEW_DIR"
          ls -ltr $NEW_DIR
          echo $BUILD >> $NEW_DIR/newfile
          cat $NEW_DIR/newfile
        env:
          NEW_DIR: ${{ github.workspace }}/newdir
          BUILD: ${{ github.sha }}

  anotations:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [ foo, bar ]
    steps:
      - run: echo "::notice::$IMAGE:$TAG"
        env:
          IMAGE: ${{ matrix.container }}
          TAG: latest
          
  reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      username: ${{ github.actor }}

#   fail:
#     runs-on: ubuntu-latest
#     steps:
#       - run: exit 1

  windows:
    runs-on: windows-2019
    steps:
      - shell: powershell
        run: |
          Install-Module -Name AWS.Tools.Installer -Force
          Install-AWSToolsModule AWS.Tools.EC2 -Force
          $Filter = @{ Name="name"; Values="Windows_Server-2019-English-Full-Base*" }
          $Ec2Images = Get-EC2Image -Owner '801119661308' -Filter $Filter
